# Copyright 2023 Deutsche Telekom MMS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# private keys, api keys etc.
secrets: {}

# environment variables
env:
  # log level of bridge
  # possible values: info, debug, warn etc.
  LOG_LEVEL: "debug"

cache:
  enabled: "true"
  # key group for redis cache
  # set name of respective bridge
  cacheKeyGroup: ""
  cacheType: "redis"
  cacheRedisHost: ""
  cacheMaxAge: "60000"
  cacheKeyIgnoredProps: "meta"

replicaCount: 1

# settings for the image
image:
  registry: ""
  repository: ""
  pullPolicy: "IfNotPresent"
  tag: ""

imagePullSecrets:
  - name: ""
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: "ClusterIP"
  port: 80

resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"

nodeSelector: {}

tolerations: []

affinity: {}
...
